development:
  adapter: redis
  channel_prefix: web_socket_tennis_development

test:
  adapter: redis
  channel_prefix: web_socket_tennis_test

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: web_socket_tennis_production
